using System.Collections.Generic;
using TimeTable.Common.AppConstants;
using TimeTable.Model;

namespace TimeTable.DAL {
	public partial class DbInitializer {
		public IEnumerable<Teacher> TeacherData { get; set; } = new List<Teacher> {
			Teacher.Create((int)Teachers.Городецький, "Городецький", "Василь", "Васильович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Житарюк, "Житарюк", "Іван", "Васильович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Сікора, "Сікора", "Віра", "Степанівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Боднарук, "Боднарук", "Свiтлана", "Богданiвна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.МартинюкО, "Мартинюк", "Ольга", "Василівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Колісник, "Колісник", "Руслана", "Степанівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.МартинюкС, "Мартинюк", "Сергій", "Васильович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Мироник, "Мироник", "Вадим", "Ілліч", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.ЛучкоВС, "Лучко", "Вікторія", "Сергіївна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Матійчук, "Матійчук", "Михайло", "Іванович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.ЛенюкМ, "Ленюк", "Михайло", "Павлович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Петришин, "Петришин", "Роман", "Іванович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Пукальський, "Пукальський", "Іван", "Дмитрович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Блажевський, "Блажевський", "Степан", "Георгійович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Лусте, "Лусте", "Ірина", "Петрівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Перун, "Перун", "Галина", "Михайлівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.ЛенюкО, "Ленюк", "Олег", "Михайлович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.ЛучкоВМ, "Лучко", "Володимир", "Миколайович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Мельничук, "Мельничук", "Лілія", "Михайлівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Тупкало, "Тупкало", "Іван", "Степанович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Ісарюк, "Ісарюк", "Інна", "Михайлівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Черевко, "Черевко", "Ігор", "Михайлович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Піддубна, "Піддубна", "Лариса", "Андріївна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Кушнірчук, "Кушнірчук", "Василь", "Йосипович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Готинчан, "Готинчан", "Тетяна", "Іванівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Клевчук, "Клевчук", "Іван", "Іванович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Пасічник, "Пасічник", "Галина", "Савелівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Івасюк, "Івасюк", "Галина", "Петрівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Караванова, "Караванова", "Тетяна", "Петрівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Матвій, "Матвій", "Олександр", "Васильович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Фратавчан, "Фратавчан", "Тоня", "Михайлівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Нестеренко, "Нестеренко", "Василь", "Володимирович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Горбатенко, "Горбатенко", "Микола", "Юрійович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Перцов, "Перцов", "Андрій", "Сергійович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Ілліка, "Ілліка", "Світлана", "Анатоліївна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Шкільнюк, "Шкільнюк", "Дмитро", "Валерійович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Строєв, "Строєв", "Олександр", "Миколайович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Дорош, "Дорош", "Андрій", "Богданович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Малик, "Малик", "Ігор", "Володимирович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Ясинський, "Ясинський", "Володимир", "Кирилович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Антонюк, "Антонюк", "Світлана", "Володимирівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Дорошенко, "Дорошенко", "Ірина", "Вікторівна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Лукашів, "Лукашів", "Тарас", "Олегович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Юрченко, "Юрченко", "Ігор", "Валерійович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.МаслюченкоВ, "Маслюченко", "Володимир", "Кирилович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.МаслюченкоО, "Маслюченко", "Олександр", "Володимирович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Михайлюк, "Михайлюк", "Володимир", "Васильович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Попов, "Попов", "Михайло", "Михайлович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.ЛінчукС, "Лінчук", "Степан", "Степанович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.ЛінчукЮ, "Лінчук", "Юрій", "Степанович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Бігун, "Бігун", "Ярослав", "Йосипович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Данилюк, "Данилюк", "Іван", "Михайлович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Краснокутська, "Краснокутська", "Інесса", "Володимирівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Любарщук, "Любарщук", "Євген", "Анатолійович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Маценко, "Маценко", "Василь", "Григорович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Мельник, "Мельник", "Галина", "Василівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Романенко, "Романенко", "Наталія", "Вікторівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Скутар, "Скутар", "Ігор", "Дмитрович", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Сопронюк, "Сопронюк", "Тетяна", "Миколаївна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Філіпчук, "Філіпчук", "Микола", "Петрович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Чикрій, "Чикрій", "Аркадій", "Олексійович", Dom.DomainValue.FullProfesor),
			Teacher.Create((int)Teachers.Шепетюк, "Шепетюк", "Богдан", "Дмитрович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Юрійчук, "Юрійчук", "Анастасія", "Олександрівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Фотій, "Фотій", "Олена", "Григорівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Звоздецький, "Звоздецький", "Тарас", "Іванович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Карлова, "Карлова", "Олена", "Олексіївна", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Сергеєва, "Сергеєва", "Лідія", "Миколаївна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Довгей, "Довгей", "Жанна", "Іллівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Собчук, "Собчук", "Олександр", "Васильович", Dom.DomainValue.AssociateProfessor),
			Teacher.Create((int)Teachers.Гуцул, "Гуцул", "Тетяна", "Олександрівна", Dom.DomainValue.AssistantProfessor),
			Teacher.Create((int)Teachers.Літовченко, "Літовченко", "", "", Dom.DomainValue.FullProfesor)
		};
	}
}