using System.Collections.Generic;
using TimeTable.Model;

namespace TimeTable.DAL {
	public partial class DbInitializer {
		public IEnumerable<Subject> SubjectData { get; set; } = new List<Subject> {

			new Subject { Id = (int)Subjects.Мат_аналіз, Name = "Мат. аналіз" },
			new Subject { Id = (int)Subjects.Програмування, Name = "Програмування" },
		//	new Subject { Id = (int)Subjects.Іноземна, 		Name ="Іноземна" },
			new Subject { Id = (int)Subjects.Дискретна_математика, Name = "Дискретна математика" },
			new Subject { Id = (int)Subjects.Алгебра_і_геометрія, Name = "Алгебра і геометрія" },
			new Subject { Id = (int)Subjects.Історія_України, Name = "Історія України" },
			new Subject { Id = (int)Subjects.Олімп_задачі_з_інформатики, Name = "Олімп. задачі з інформатики" },
			new Subject { Id = (int)Subjects.Основи_інформаційних_техн_, Name = "Основи інформаційних техн." },
			new Subject { Id = (int)Subjects.Лінійна_алгебра, Name = "Лінійна алгебра" },
			new Subject { Id = (int)Subjects.Пакети_прикладних_програм, Name = "Пакети прикладних програм" },
			new Subject { Id = (int)Subjects.Матем_логіка_та_теорія_алгоритмів, Name = "Матем логіка та теорія алгоритмів" },
			new Subject { Id = (int)Subjects.Громадське_здоров_я_та_медицина, Name = "Громадське здоров'я та медицина" },
			new Subject { Id = (int)Subjects.Обчислювальна_геометрія_та_комп_графіка, Name = "Обчислювальна геометрія та комп. графіка" },
			new Subject { Id = (int)Subjects.Об_єкто_орієнтоване_програмування, Name = "Об'єкто-орієнтоване програмування" },
			new Subject { Id = (int)Subjects.Розробка_UI_UX_дизайну, Name = "Розробка UI/UX дизайну" },
			new Subject { Id = (int)Subjects.Диф_рівняння, Name = "Диф. рівняння" },
			new Subject { Id = (int)Subjects.Комп_ютерна_математика, Name = "Комп'ютерна математика" },
			new Subject { Id = (int)Subjects.Основи_інформаційної_безпеки, Name = "Основи інформаційної безпеки" },
			new Subject { Id = (int)Subjects.ПЗОС, Name = "ПЗОС" },
			new Subject { Id = (int)Subjects.Алгебра_і_теорія_чисел, Name = "Алгебра і теорія чисел" },
			new Subject { Id = (int)Subjects.Методика_соціально_виховної_роботи_в_сучасній_школі, Name = "Методика соціально-виховної роботи в сучасній школі" },
			new Subject { Id = (int)Subjects.Програмування_та_підтримка_веб_застосувань, Name = "Програмування та підтримка веб-застосувань" },
			new Subject { Id = (int)Subjects.Економіка_основи_бух_обліку, Name = "Економіка (основи бух обліку)" },
			new Subject { Id = (int)Subjects.Спеціалізовані_мови_програмування, Name = "Спеціалізовані мови програмування" },
			new Subject { Id = (int)Subjects.Мод_жорст_сист_на_ЕОМ, Name = "Мод. жорст. сист. на ЕОМ" },
			new Subject { Id = (int)Subjects.Рівняння_з_частинними_похідними, Name = "Рівняння з частинними похідними" },
			new Subject { Id = (int)Subjects.Педагогічна_психологія, Name = "Педагогічна психологія" },
			new Subject { Id = (int)Subjects.ТЙМС, Name = "ТЙМС" },
			new Subject { Id = (int)Subjects.Методи_обчислень, Name = "Методи обчислень" },
			new Subject { Id = (int)Subjects.Рівняння_математичної_фізики, Name = "Рівняння математичної фізики" },
			new Subject { Id = (int)Subjects.Visual_Basic_та_його_діалекти, Name = "Visual Basic та його діалекти" },
			new Subject { Id = (int)Subjects.Технології_програмування_на_Java, Name = "Технології програмування на Java" },
			new Subject { Id = (int)Subjects.Інформаційні_технології_в_економіці, Name = "Інформаційні технології в економіці" },
			new Subject { Id = (int)Subjects.Основи_Internet_технологій, Name = "Основи Internet-технологій" },
			new Subject { Id = (int)Subjects.Сучасні_СУБД, Name = "Сучасні СУБД" },
			new Subject { Id = (int)Subjects.Психологія_та_МСВР, Name = "Психологія та МСВР" },
			new Subject { Id = (int)Subjects.Економіка, Name = "Економіка" },
			new Subject { Id = (int)Subjects.Інф_техн_в_сист_аналізі, Name = "Інф. техн. в сист. аналізі" },
			new Subject { Id = (int)Subjects.Комп_ютерне_моделювання_природних_процесів, Name = "Комп'ютерне моделювання природних процесів" },
			new Subject { Id = (int)Subjects.Диференціальна_геометрія_і_топологія, Name = "Диференціальна геометрія і топологія" },
			new Subject { Id = (int)Subjects.Комплексний_аналіз, Name = "Комплексний аналіз" },
			new Subject { Id = (int)Subjects.Основи_теорії_груп, Name = "Основи теорії груп" },
			new Subject { Id = (int)Subjects.Теорія_міри_та_інтеграла, Name = "Теорія міри та інтеграла" },
			new Subject { Id = (int)Subjects.Узагальнення_функції_та_їх_застосування_у_МФ, Name = "Узагальнення функції та їх застосування у МФ" },
			new Subject { Id = (int)Subjects.Загальна_теорія_функцій, Name = "Загальна теорія функцій" },
			new Subject { Id = (int)Subjects.Проектування_програмних_систем, Name = "Проектування програмних систем" },
			new Subject { Id = (int)Subjects.Програмування_мовою_Python, Name = "Програмування мовою Python" },
			new Subject { Id = (int)Subjects.Математична_економіка, Name = "Математична економіка" },
			new Subject { Id = (int)Subjects.Випадкові_процеси, Name = "Випадкові процеси" },
			new Subject { Id = (int)Subjects.Методи_оптимізації, Name = "Методи оптимізації" },
			new Subject { Id = (int)Subjects.Інф_технології_управління, Name = "Інф технології управління" },
			new Subject { Id = (int)Subjects.Математичне_моделювання_та_системний_аналіз, Name = "Математичне моделювання та системний аналіз" },
			new Subject { Id = (int)Subjects.Прикладний_статистичний_аналіз, Name = "Прикладний статистичний аналіз" },
			new Subject { Id = (int)Subjects.Інформаційні_системи_обліку, Name = "Інформаційні системи обліку" },
			new Subject { Id = (int)Subjects.Статистичне_моделювання, Name = "Статистичне моделювання" },
			new Subject { Id = (int)Subjects.Front_end_робробка_веб_додатків, Name = "Front-end робробка веб-додатків" },
			new Subject { Id = (int)Subjects.Теорія_керування, Name = "Теорія керування" },
			new Subject { Id = (int)Subjects.Інф_системи_менеджменту_та_маркетингу, Name = "Інф системи менеджменту та маркетингу" },
			new Subject { Id = (int)Subjects.Методика_викладання_математики_та_інформатики, Name = "Методика викладання математики та інформатики" },
			new Subject { Id = (int)Subjects.Платформи_корпоративних_інформаційних_систем, Name = "Платформи корпоративних інформаційних систем" },
			new Subject { Id = (int)Subjects.Теорія_програмування, Name = "Теорія програмування" },
			new Subject { Id = (int)Subjects.Гіперкомплексні_системи, Name = "Гіперкомплексні системи" },
			new Subject { Id = (int)Subjects.Елементарна_математика_та_методика_викладання, Name = "Елементарна математика та методика викладання" },
			new Subject { Id = (int)Subjects.Геометричні_перетворення, Name = "Геометричні перетворення" },
			new Subject { Id = (int)Subjects.Математична_логіка, Name = "Математична логіка" },
			new Subject { Id = (int)Subjects.Математична_статистика_з_елементами_теорії_випадкових_процесів, Name = "Математична статистика з елементами теорії випадкових процесів" },
			new Subject { Id = (int)Subjects.КЗ_для_ПР_2_го_порядку, Name = "КЗ для ПР 2-го порядку" },
			new Subject { Id = (int)Subjects.ЕКЗ_2_го_П, Name = "ЕКЗ 2-го П" },
			new Subject { Id = (int)Subjects.ГБП, Name = "ГБП" },
			new Subject { Id = (int)Subjects.Теоретична_механіка, Name = "Теоретична механіка" },
			new Subject { Id = (int)Subjects.ТВП, Name = "ТВП" },
			new Subject { Id = (int)Subjects.Захист_інформації_в_БД, Name = "Захист інформації в БД" },
			new Subject { Id = (int)Subjects.Індивід_робота_СЗІ, Name = "Індивід робота СЗІ" },
			new Subject { Id = (int)Subjects.Розробка_крос_платформенних_додатків, Name = "Розробка крос-платформенних додатків" },
			new Subject { Id = (int)Subjects.Системи_захисту_інформації, Name = "Системи захисту інформації" },
			new Subject { Id = (int)Subjects.Інформаційний_менеджмент_проектів, Name = "Інформаційний менеджмент проектів" },
			new Subject { Id = (int)Subjects.Технологія_розробки_РБД, Name = "Технологія розробки РБД" },
			new Subject { Id = (int)Subjects.Комунікації_та_теорія_конфліктів, Name = "Комунікації та теорія конфліктів" },
			new Subject { Id = (int)Subjects.Java_технології_клієнт_серверних_систем, Name = "Java-технології клієнт-серверних систем" },
			new Subject { Id = (int)Subjects.ММДС, Name = "ММДС" },
			new Subject { Id = (int)Subjects.ККПтаМН, Name = "ККПтаМН" },
			new Subject { Id = (int)Subjects.ВРМПН, Name = "ВРМПН" },
			new Subject { Id = (int)Subjects.Технології_робробки_ІС, Name = "Технології робробки ІС" },
			new Subject { Id = (int)Subjects.Теорія_і_практика_бізнес_планування, Name = "Теорія і практика бізнес планування" },
			new Subject { Id = (int)Subjects.Сіткове_планування, Name = "Сіткове планування" },
			new Subject { Id = (int)Subjects.МТІМСуЗММ, Name = "МТІМСуЗММ" },
			new Subject { Id = (int)Subjects.ЕР_та_М_його_М, Name = "ЕР та М його М" },
			new Subject { Id = (int)Subjects.Методика_викладання_математики_та_інформатики_у_ВНЗ, Name = "Методика викладання математики та інформатики у ВНЗ" },
			new Subject { Id = (int)Subjects.РПД_для_МП, Name = "РПД для МП" },
			new Subject { Id = (int)Subjects.Охорона_праці_в_галузі, Name = "Охорона праці в галузі" },
			new Subject { Id = (int)Subjects.Програмні_засоби_управління_проектами, Name = "Програмні засоби управління проектами" },
			new Subject { Id = (int)Subjects.Розробка_пр_додатків_для_мобільних_пристроїв, Name = "Розробка пр додатків для мобільних пристроїв" },
			new Subject { Id = (int)Subjects.КЗІБ, Name = "КЗІБ" },
			new Subject { Id = (int)Subjects.Педагогіка_та_психологія_у_ВШ, Name = "Педагогіка та психологія у ВШ" },
			new Subject { Id = (int)Subjects.Моделі_виживання, Name = "Моделі виживання" },
			new Subject { Id = (int)Subjects.СЙЗОК_та_їх_Р_на_ПК, Name = "СЙЗОК та їх Р на ПК" },
			new Subject { Id = (int)Subjects.Стохастичне_моделювання, Name = "Стохастичне моделювання" },
			new Subject { Id = (int)Subjects.Математика_фінансів, Name = "Математика фінансів" },
			new Subject { Id = (int)Subjects.Стат_мод_у_ризик_страхув, Name = "Стат мод у ризик страхув" },
			new Subject { Id = (int)Subjects.Сучасні_комп_моделі_ринку_цінних_паперів, Name = "Сучасні комп. моделі ринку цінних паперів" },
			new Subject { Id = (int)Subjects.КСППР, Name = "КСППР" },
			new Subject { Id = (int)Subjects.Стохастичне_прогнозування_на_ПК, Name = "Стохастичне прогнозування на ПК" },
			new Subject { Id = (int)Subjects.Науковий_семінар, Name = "Науковий семінар" },
			new Subject { Id = (int)Subjects.Аналітична_геометрія, Name = "Аналітична геометрія" },
			new Subject { Id = (int)Subjects.Операційні_системи_та_системне_програмування, Name = "Операційні системи та системне програмування" },
			new Subject { Id = (int)Subjects.Бази_данних_та_Інформаційні_системи, Name = "Бази данних та Інформаційні системи" }
		};
	}
}